policy_path: "/home/pcrn/unitree_rl_gym/logs/g1/exported/policies/policy_lstm_1.pt"

xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene.xml"

simulation_duration: 60.0
simulation_dt: 0.002
control_decimation: 10

kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0.5, 0, 0]
